# Generated by Django 4.1.7 on 2023-10-14 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendHomework', '0002_remove_homework_image_alter_homework_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('class_num', models.IntegerField()),
                ('number', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Homework',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
